#!/bin/bash

# if you want to use your own template, set the variable below fore example
# TEMPLATE="$HOME/.pandoc/templates/default.beamer"
TEMPLATE=
# you could change the variable below to pdflatex if you prefer that
LATEX=xelatex
# set the variable below if you want to view the pdf in that viewer
PDFVIEWER=

function split_path () {
    fname_with_ext=${1##*/}
    fname_sans_ext=${fname_with_ext%.*}
    if [[ $1 = */* ]] ; then
        relative_dirname=${1%/*}
    else
        relative_dirname=.
    fi
    absolute_dirname=`realpath $relative_dirname`
}

split_path $1

md_file=$fname_with_ext
tex_file="${fname_sans_ext}.tex"
pdf_file="${fname_sans_ext}.pdf"

cd $relative_dirname

if [ ! -z "$TEMPLATE" ]; then
    TEMPLATE_OPTION="--template $TEMPLATE"
fi

pandoc -t beamer -s $md_file $TEMPLATE_OPTION -o $tex_file && \
    $LATEX $tex_file -halt-on-error && \
    $LATEX $tex_file -halt-on-error
if [[ $? == 0 && ! -z $PDFVIEWER ]] ; then
    $PDFVIEWER $pdf_file
fi
if command -v txclean.py >/dev/null ; then
    txclean.py $tex_file
else
    echo "txclean.py not found. Intermediate files not deleted."
fi



